### ISSUE TITLE
Foute spelling

### ISSUE THREAD

**Issue by Mohagames205** [YasinJS/ComponentJS#1]
Dit is fout gespeld https://github.com/YasinJS/ComponentJS/blob/main/App/main.js#L15

**Comment by Yasintje** [comment]
Thank you for opening this issue this has already been fixed in the development branch.
Currently i am working in the dev branch all the changes that are made will be moved to the main branch asap.

**Comment by Mohagames205** [comment]
No it's still spelled wrong in the dev branch

https://github.com/YasinJS/ComponentJS/blob/dev/App/main.js#L19

**Comment by Yasintje** [comment]
I haven't pushed it yet 😛
